sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.6
install:
  - pip install nose
script:
  - python ./elixir_sense.py
  - python -m unittest t.erl_terms_test
notifications:
  irc: "irc.freenode.org#vim-elixir"
